// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "enableAuto": boolean;
      "enableDict": boolean;
      "enablePopup": boolean;
      "enableComment": boolean;
      "enableAnnotationFromSyncTranslation": boolean;
      "annotationTranslationPosition": string;
      "enableNote": boolean;
      "enableNoteReplaceMode": boolean;
      "translateSource": string;
      "dictSource": string;
      "sourceLanguage": string;
      "targetLanguage": string;
      "fontSize": string;
      "lineHeight": string;
      "splitChar": string;
      "rawResultOrder": boolean;
      "showItemMenuTitleTranslation": boolean;
      "showItemMenuAbstractTranslation": boolean;
      "showSidebarEngine": boolean;
      "showSidebarSettings": boolean;
      "showSidebarConcat": boolean;
      "showSidebarLanguage": boolean;
      "showSidebarRaw": boolean;
      "showSidebarCopy": boolean;
      "showItemBoxTitleTranslation": boolean;
      "showItemBoxAbstractTranslation": boolean;
      "keepWindowTop": boolean;
      "keepPopupSize": boolean;
      "popupWidth": number;
      "popupHeight": number;
      "niutransEndpoint": string;
      "niutransUsername": string;
      "niutransPassword": string;
      "niutransDictNo": string;
      "niutransMemoryNo": string;
      "niutransDictLibList": string;
      "niutransMemoryLibList": string;
      "autoPlay": boolean;
      "showPlayBtn": boolean;
      "enableAutoDetectLanguage": boolean;
      "disabledLanguages": string;
      "extraEngines": string;
      "titleColumnMode": string;
      "chatGPT.endPoint": string;
      "chatGPT.model": string;
      "chatGPT.temperature": string;
      "chatGPT.prompt": string;
      "chatGPT.stream": boolean;
      "azureGPT.endPoint": string;
      "azureGPT.model": string;
      "azureGPT.apiVersion": string;
      "azureGPT.temperature": string;
      "azureGPT.prompt": string;
      "azureGPT.stream": boolean;
      "gemini.endPoint": string;
      "gemini.prompt": string;
      "gemini.stream": boolean;
      "cnkiRegex": string;
      "cnkiSplitSecond": number;
      "cnkiUseSplit": boolean;
      "deeplx.endpoint": string;
      "qwenmt.endPoint": string;
      "qwenmt.model": string;
      "qwenmt.domains": string;
      "aliyun.action": string;
      "aliyun.scene": string;
    };
  }
}
