name: Bug report
description: File a bug / issue
title: "[Bug] "
labels:
  - bug
  # - Needs Triage
assignees: windingwind
body:
  - type: checkboxes
    id: check-search
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true

  - type: checkboxes
    id: check-frequent
    attributes:
      label: Have you checked the FAQ (#6)?
      description: Please check the FAQ to see if your question has already been answered.
      options:
        - label: I have checked the FAQ
          required: true

  - type: checkboxes
    id: check-version
    attributes:
      label: Are you using the latest Zotero and the latest plugin?
      description: Only bug reports that can be reproduced on the latest Zotero and plugin will be considered.
      options:
        - label: I have confirmed I'm using the latest Zotero and the latest plugin
          required: true

  - type: textarea
    attributes:
      label: Environment
      description: |
        examples:
          - **OS**: Windows 11 22H2
          - **Zotero Version**: 7.0.0
          - **Plugin Version**: 1.0.0
      value: |
        - OS: 
        - Zotero Version: 
        - Plugin Version: 
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: |
        A clear and concise description of what the bug is.
        If applicable, add screenshots and log to help explain your problem.
    validations:
      required: true

  - type: textarea
    id: debug-output
    attributes:
      label: Debug Output
      description: |
        Steps to get debug output:
        1. Disable all other plugins, exit Zotero, and restart Zotero
        2. menu -> `Help` -> `Debug Output` -> `View Output`
        3. Do steps to reproduce the bug
        4. In the debug output window, press `Ctrl/Cmd + S`
        5. Upload the debug output here
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
