name: Feature request
description: Suggest an idea for this project
title: "[Feature] "
labels:
  - enhancement
assignees: windingwind
body:
  - type: checkboxes
    id: check-search
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for this feature request.
      options:
        - label: I have searched the existing issues
          required: true

  - type: textarea
    attributes:
      label: Environment
      description: |
        examples:
          - **OS**: Windows 11 22H2
          - **Zotero Version**: 7.0.0
          - **Plugin Version**: 1.0.0
      value: |
        - OS: 
        - Zotero Version: 
        - Plugin Version:
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the feature request
      value: |
        **Is your feature request related to a problem? Please describe.**
        A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

        **Why do you need this feature?**
        A clear and concise description of why you need this feature.
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      value: |
        **The solution you'd like**
        A clear and concise description of what you want to happen.

        **Alternatives you've considered**
        A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
